version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    container_name: db
    image: "mysql:latest"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "blog"
      MYSQL_ROOT_PASSWORD: "123"
    expose:
      - 3306
    ports:
      - 3366:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 60s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
